name: 'Setup Onescript Action'
description: 'Setup your runner with Onescript'
branding:
  icon: 'chevrons-down'
  color: 'blue'
author: 'otymko'
inputs: 
  version:
    description: 'Version of Onescript to use. Support value: 1.3.0, 1.5.0, 1.8.1, dev'
    required: true
  ovm_version:
    description: 'Version of Onescript manager to use. Support value: 1.1.0, 1.2.0, latest'
    required: false
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'
