name: "Check setup"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: oscript for linux
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        version: 1.3.0
    - name: Проверка скрипта OS
      run: oscript test/fixtures/test.os
    # runs-on: windows-latest
    # name: oscript for win
    # steps:
    # - uses: actions/checkout@v1
    # - uses: ./
    #   with:
    #     version: 1.3.0
    # - name: Проверка скрипта OS
    #   run: oscript test/fixtures/test.os