name: "Check setup"
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        oscript_version: [dev]
        os: [windows-latest]
    name: check oscript
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        version: ${{ matrix.oscript_version }}
    - name: Проверка скрипта OS
      run: oscript test/fixtures/test.os
